language: node_js
sudo: required
dist: trusty
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "l/GgknZ4N4dZo2D1TSzgbS3WSaLK3Xwde+KLFUmSvbN/bUPEIS+QSzhkjmgrtVlVZ57wLkW+bSMMBLdqQdXlDM2ThQtN9ZBNCeN5k6o0kvs9s4pKGAjO7oyVMzpYvuzRI1piAZk1POtm1Hi6ywvEVQj+e/LS0yo0Xtt3IxkgKBc5yA8lywcVURRKPMTmfY0/GJz1tZo5quS879CyNwy4Hvd+xa3GmOvNMSqT/wBjtLomymGh8h6UgtEuy0d4RiQExezORjjqtaP4X7LCh3mnpmvyqBHF2dGsPfb2nj1biz9vKKZjWVGnVdpKQDH6jJOOLHCxrPPklOXLe0TIYLSCY0DMqbeMELxs2K6Btv3D/a6BiiikwHgymcD0CwAx1cL/fvrMZhcR2p6ey3Vkm/sphX6Gh1JnEr9AD4G73069p5pM/Zopujd5KBgUlDVtgjFD7ADwc0aeNOr5TqIGPgmy/GPWWylJi62KpT3rPYEhCbhYI9SQOf1EGS/LpysXyRQ2iTaiOlerEZ1n7c4O35okL61JcWOSWAwBOmXaNUJvmbcASCl2F3cOhUNrlzkJQncIRQcx/HNAWOahAu/36DEj7mhuveC+1Y2yfsRGIcyZWeybINXjXakJV2UXbjr1mayI9EIPX6Xe3AZa27d+HpYmpow7cR32AP1yLBc8XDGfUCM="
before_install:
   - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: "Teradata/nodejs-driver"
      description: "Teradata Node.js Driver"
    notification_email: jeremy.smartt@teradata.com
    build_command_prepend: "npm run build"
    build_command: "--no-command --fs-capture-search dist/"
    branch_pattern: coverity_scan
node_js:
- '10.15.3'
branches:
  only:
    - coverity_scan
jobs:
  include:
    - env: "MODE=coverity"
install:
  # Work around broken certificate of scan.coverity.com
  - sudo curl -s -L https://entrust.com/root-certificates/entrust_l1k.cer -o /usr/local/share/ca-certificates/entrust_l1k.crt
  - sudo update-ca-certificates
  - npm install
script:
- ./scripts/ci/travis-script.sh
cache:
  directories:
    - ./node_modules/
