language: node_js
sudo: required
dist: trusty

node_js:
- '12.18.0'
branches:
  only:
    - master
    - develop
jobs:
  include:
    - env: "MODE=lint"
    - env: "MODE=audit"
install:
- npm install
script:
- ./scripts/ci/travis-script.sh
cache:
  directories:
    - ./node_modules/
