language: node_js
sudo: required
dist: trusty
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "kohZLa9oJRF4I4uMwa8vgHICrj0AqJ/vb1uC2HX+vEIm0hYvfGRQs6uiz4tMeXRZkr+14w8OVyD9dMT3Oke0+PqlM7rBhXc3pCYp9nGyaDt0+wZlDlmh49AO/KK/u+cAFi1fU8p/7hpYfYlTi0lCjZ5asbQtDbJmL9zVALuCpLNpit8gp+SYzTqkyo0X2FAuFkDSsSmTHYHcFBfj2JwW7we+ExYinY4NSRnFNN3+8Ihe1zsi0B8hPHLuouWgRKjQFBEqlmqZydEyHgO9MSmyrDYJZUIQbbsJHu+c50HH4S0M9Ni/hMjXsUreLysgZSIC9TG/akBVXxdGyqUCyt+mNjppT0vwmWV+4GcEo43Ww7cB8vA3T0Srt0koZG1jd8lH21ugOnKXMVsZAfPIMmr8ToDV+2UHK6bcBfpjU0PF/evEnXvMAbxwtZphumIzx3+wKs69ImmaFMA80IYKB1SnBE3mH3qZ8oCTVh7Qd4d8p2oX4qAGNRZvNLp9HaO/Jzox8YIYLcPj6Lwa7nSFlQaVxAAiI4gy6wOannyprRVVZVUx7SJgCn2PLBVEYinyBzSefSUDBVTRlQYuz7dQmH2O3MQeMG8nGtPcdZ4+7rpgrnvIMb0l0igBFBWF5gtzsxMf+fJR+K7wk4CFETT9qptjonHuRuf9wFcgkHZsua2iIIE="
before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: "Teradata/nodejs-driver"
      description: "Teradata Node.js Driver"
    notification_email: jeremy.smartt@teradata.com
    build_command_prepend: "npm run build"
    build_command: "--no-command --fs-capture-search dist/"
    branch_pattern: coverity_scan
  apt:
    packages:
      - libssl
node_js:
- '10.15.3'
branches:
  only:
    - coverity_scan
jobs:
  include:
    - env: "MODE=coverity"
install:
- npm install
script:
- ./scripts/ci/travis-script.sh
cache:
  directories:
    - ./node_modules/
