language: node_js
sudo: required
dist: trusty

node_js:
- '8.9.4'
branches:
  only:
    - master
    - develop
jobs:
  include:
    - env: "MODE=lint"
install:
- npm install
script:
- ./scripts/ci/travis-script.sh
cache:
  directories:
    - ./node_modules/
