name: CD Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Semantic version of the release'
        required: true

jobs:
  cdRelease:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: npm
      - run: npm install
      - name: bump version
        shell: bash
        run: |
          export PATH=$PATH:./node_modules/.bin
          git config --global user.email "developers@teradata.com"
          git config --global user.name "Teradata GitHub Actions"
          bump $RELEASE_VERSION --commit --tag --push package.json package-lock.json docs/SETUPRUNNING.md README.md
        env:
          RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
      - run: npm run build-and-publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.event.inputs.releaseVersion }}
          release_name: teradata-nodejs-driver v${{ github.event.inputs.releaseVersion }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false
      - name: reset changelog
        shell: bash
        run: |
          cp CHANGELOG.md.template CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "resetting CHANGELOG.md for the next release"
          git push origin
